# --------------------( LICENSE                            )--------------------
# Copyright (c) 2023-2025 Alexis Pietak & Cecil Curry.
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                           )--------------------
# Project-wide MkDocs configuration, applied to all invocations of the MkDocs
# documentation generator within this project -- including both by directly
# running the external "mkdocs" command locally and by indirectly running that
# command remotely from GitHub Actions-based documentation workflows.
#
# --------------------( COMMANDS                           )--------------------
# Commonly used MkDocs commands include:
#     # Add a default MkDocs documentation tree to the current project:
#     cd ~/py/${PROJECT_NAME}
#     mkdocs new .
#
#     # Locally test the current MkDocs documentation tree:
#     mkdocs serve
#
#     # Remotely push to the GitHub Pages-hosted Project Site:
#     mkdocs gh-deploy

# ....................{ MAIN                                }...................
site_name: Cellnition

# ....................{ PLUGINS                             }...................
# Third-party MkDocs plugins currently employed by this project.
plugins:
  # Automatically generate API reference documentation from Python docstrings
  # embedded inside the Python package defined by this project. See also:
  #     https://github.com/mkdocstrings/mkdocstrings
  - mkdocstrings:
      handlers:
        python:
          # List of all inventories (i.e., external URLs to Sphinx-formatted
          # inventory files listing all Python attributes provided by the APIs
          # hosted at those URLs). Third-party attributes provided by an
          # inventory listed below will be implicitly linked to; all other
          # third-party attributes will remain unlinked.
          inventories:
            # Official inventory providingS
            # * All Python builtins.
            # * The standard Python library.
            - https://docs.python.org/3/objects.inv

          options:
            # Prefer NumpyDoc-style Python docstrings. By default, "mkdocstrings"
            # assumes Google-style Python docstrings.
            docstring_style: numpy

          # List of all dirnames relative to this configuration file under which
          # to discover documentation.
          paths:
            # The current working directory.
            - "."

# ....................{ THEME                               }...................
# Third-party MkDocs UI theme currently employed by this project.
theme:
  # See also:
  #     https://squidfunk.github.io/mkdocs-material
  name: material
